sudo: false
language: java
jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn clean package

env:  
  - DOCKER_IMAGE_NAME=swaggerapi/swagger-validator

after_success:
  - if [ $DOCKER_HUB_USERNAME ]; then
      docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD;

      if [ ! -z "$TRAVIS_TAG" ]; then
        DOCKER_IMAGE_TAG=$TRAVIS_TAG;
      else
        DOCKER_IMAGE_TAG=unstable;
      fi;
      docker build -t $DOCKER_IMAGE_NAME .;
      if [ ! -z "$TRAVIS_TAG" ]; then
        docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG;
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG;
        docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest;
        docker push $DOCKER_IMAGE_NAME:latest;
      else
        docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG;
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG;
      fi;
    fi;
